import type {
  AgentCardSource,
  ApprovalPolicySource,
  JsonSchema,
  MemoryPolicySource,
  ModelPolicySource,
  ToolDescriptorSource,
} from "./contracts";

const SOURCE_COMMIT = "7bc813df452e9ac255a087cfcaa4ae70474d4c42";
const CONTEXT_SOURCE_COMMIT = "cd86f65ceb0bd1b668324e7d523d5a49568461c7";
const CREATED_AT = "2026-07-16T18:00:00.000Z";
const APPROVAL = {
  approvedBy: "Synthetic control reviewer",
  approvedAt: "2026-07-16T19:00:00.000Z",
  approvalPolicyId: "policy.registry.separation-of-duties",
  decisionRecordId: "decision.synthetic.registry-v1",
} as const;

const INPUT_SCHEMA_REF = { $ref: "/capabilities/schemas/stage-input.schema.json" } as const;
const OUTPUT_SCHEMA_REF = { $ref: "/capabilities/schemas/stage-output.schema.json" } as const;

const stringField = { type: "string", minLength: 1 } as const;
const stringArray = { type: "array", items: stringField, uniqueItems: true } as const;

function objectSchema(
  properties: Readonly<Record<string, JsonSchema>>,
  required: readonly string[],
): JsonSchema {
  return { type: "object", additionalProperties: false, properties, required };
}

function approvedTool(
  source: Omit<
    ToolDescriptorSource,
    "kind" | "status" | "sourceCommit" | "createdAt" | "updatedAt" | "approval"
  >,
): ToolDescriptorSource {
  return {
    kind: "ToolDescriptor",
    status: "APPROVED",
    sourceCommit: SOURCE_COMMIT,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    approval: APPROVAL,
    ...source,
  };
}

export const toolDescriptorSources = [
  approvedTool({
    id: "tool.issue.read",
    name: "Issue read",
    version: "1.0.0",
    description: "Reads one allow-listed synthetic issue fixture without contacting Jira.",
    riskLevel: "READ_ONLY",
    inputSchema: objectSchema({ issueKey: stringField }, ["issueKey"]),
    outputSchema: objectSchema({ issue: { type: "object" } }, ["issue"]),
    sideEffects: ["None; reads a checked-in synthetic fixture."],
    requiredScopes: ["issue:read", "tool:invoke"],
    allowedStages: ["intake", "spec", "plan"],
    timeoutMs: 1000,
    idempotency: "IDEMPOTENT",
    networkRequired: false,
    filesystemBoundary: { mode: "NONE", allowedPaths: [] },
    approvalPolicyId: null,
    sourceImplementation: {
      module: "src/demo/data/fixtures.ts",
      exportName: "issues",
    },
  }),
  approvedTool({
    id: "tool.repository.search",
    name: "Repository search",
    version: "1.0.0",
    description: "Searches text within the disposable synthetic toy repository.",
    riskLevel: "READ_ONLY",
    inputSchema: objectSchema({ query: stringField, path: stringField }, ["query"]),
    outputSchema: objectSchema({ matches: { type: "array", items: { type: "object" } } }, [
      "matches",
    ]),
    sideEffects: ["None; file reads remain inside the disposable toy repository."],
    requiredScopes: ["artifact:read", "tool:invoke"],
    allowedStages: ["spec", "plan", "targets", "implement"],
    timeoutMs: 2000,
    idempotency: "IDEMPOTENT",
    networkRequired: false,
    filesystemBoundary: { mode: "READ_ONLY", allowedPaths: ["README.md", "src/**", "test/**"] },
    approvalPolicyId: null,
    sourceImplementation: {
      module: "tools/toy-repo-mcp/server.ts",
      exportName: "registerRepositorySearch",
    },
  }),
  approvedTool({
    id: "tool.repository.file.read",
    name: "Repository file read",
    version: "1.0.0",
    description: "Reads one allow-listed UTF-8 file from the disposable synthetic toy repository.",
    riskLevel: "READ_ONLY",
    inputSchema: objectSchema({ path: stringField }, ["path"]),
    outputSchema: objectSchema({ path: stringField, contents: stringField }, ["path", "contents"]),
    sideEffects: ["None; file reads remain inside the disposable toy repository."],
    requiredScopes: ["artifact:read", "tool:invoke"],
    allowedStages: ["spec", "plan", "targets", "implement", "verify"],
    timeoutMs: 2000,
    idempotency: "IDEMPOTENT",
    networkRequired: false,
    filesystemBoundary: { mode: "READ_ONLY", allowedPaths: ["README.md", "src/**", "test/**"] },
    approvalPolicyId: null,
    sourceImplementation: {
      module: "tools/toy-repo-mcp/server.ts",
      exportName: "registerRepositoryFileRead",
    },
  }),
  approvedTool({
    id: "tool.repository.patch.controlled",
    name: "Controlled patch application",
    version: "1.0.0",
    description:
      "Replaces one exact text occurrence inside an allow-listed toy-repository source file.",
    riskLevel: "HIGH",
    inputSchema: objectSchema(
      { path: stringField, expected: stringField, replacement: stringField },
      ["path", "expected", "replacement"],
    ),
    outputSchema: objectSchema({ path: stringField, changed: { type: "boolean" } }, [
      "path",
      "changed",
    ]),
    sideEffects: ["Writes one bounded file in a disposable temporary copy after host approval."],
    requiredScopes: ["artifact:write", "tool:invoke"],
    allowedStages: ["implement"],
    timeoutMs: 3000,
    idempotency: "IDEMPOTENT",
    networkRequired: false,
    filesystemBoundary: { mode: "BOUNDED_WRITE", allowedPaths: ["src/**"] },
    approvalPolicyId: "policy.write.approved-targets",
    sourceImplementation: {
      module: "tools/toy-repo-mcp/server.ts",
      exportName: "registerControlledPatch",
    },
  }),
  approvedTool({
    id: "tool.sandbox.command",
    name: "Sandbox command execution",
    version: "1.0.0",
    description: "Runs only the fixed validation command in the disposable toy repository.",
    riskLevel: "MEDIUM",
    inputSchema: objectSchema({ command: { const: "validate" } }, ["command"]),
    outputSchema: objectSchema(
      { exitCode: { type: "integer" }, stdout: stringField, stderr: stringField },
      ["exitCode", "stdout", "stderr"],
    ),
    sideEffects: [
      "Starts a bounded local Node test subprocess; it cannot select an arbitrary command.",
    ],
    requiredScopes: ["sandbox:execute", "tool:invoke"],
    allowedStages: ["implement", "verify"],
    timeoutMs: 10000,
    idempotency: "IDEMPOTENT",
    networkRequired: false,
    filesystemBoundary: { mode: "READ_ONLY", allowedPaths: ["src/**", "test/**"] },
    approvalPolicyId: "policy.sandbox.validation-notify",
    sourceImplementation: {
      module: "tools/toy-repo-mcp/server.ts",
      exportName: "registerSandboxValidation",
    },
  }),
  approvedTool({
    id: "tool.repository.diff.inspect",
    name: "Diff inspection",
    version: "1.0.0",
    description: "Returns the sanitized Git diff for the disposable synthetic toy repository.",
    riskLevel: "READ_ONLY",
    inputSchema: objectSchema({}, []),
    outputSchema: objectSchema({ diff: { type: "string" }, changedPaths: stringArray }, [
      "diff",
      "changedPaths",
    ]),
    sideEffects: ["None; executes a fixed read-only Git diff command."],
    requiredScopes: ["artifact:read", "tool:invoke"],
    allowedStages: ["targets", "implement", "verify", "review"],
    timeoutMs: 3000,
    idempotency: "IDEMPOTENT",
    networkRequired: false,
    filesystemBoundary: { mode: "READ_ONLY", allowedPaths: ["src/**", "test/**"] },
    approvalPolicyId: null,
    sourceImplementation: {
      module: "tools/toy-repo-mcp/server.ts",
      exportName: "registerDiffInspection",
    },
  }),
  approvedTool({
    id: "tool.evidence.write",
    name: "Evidence writing",
    version: "1.0.0",
    description:
      "Writes deterministic evidence to browser-local state or a generated public fixture path.",
    riskLevel: "LOW",
    inputSchema: objectSchema({ evidenceType: stringField, payload: { type: "object" } }, [
      "evidenceType",
      "payload",
    ]),
    outputSchema: objectSchema({ evidenceId: stringField, digest: stringField }, [
      "evidenceId",
      "digest",
    ]),
    sideEffects: ["Writes only synthetic evidence within an explicitly selected local boundary."],
    requiredScopes: ["artifact:write", "tool:invoke"],
    allowedStages: ["implement", "verify", "review"],
    timeoutMs: 2000,
    idempotency: "IDEMPOTENT_WITH_KEY",
    networkRequired: false,
    filesystemBoundary: { mode: "BOUNDED_WRITE", allowedPaths: ["browser-local://evidence/**"] },
    approvalPolicyId: "policy.evidence.write",
    sourceImplementation: {
      module: "src/demo/exports/validation.ts",
      exportName: "createValidationEvidencePack",
    },
  }),
  approvedTool({
    id: "tool.workflow.diff-review",
    name: "Human diff review record",
    version: "1.0.0",
    description:
      "Records that an authorized synthetic code-reviewer persona inspected a demo diff.",
    riskLevel: "LOW",
    inputSchema: objectSchema({ issueKey: stringField, diffDigest: stringField }, [
      "issueKey",
      "diffDigest",
    ]),
    outputSchema: objectSchema({ reviewRecorded: { type: "boolean" } }, ["reviewRecorded"]),
    sideEffects: ["Updates browser-local synthetic review state only."],
    requiredScopes: ["diff:review", "tool:invoke"],
    allowedStages: ["review"],
    timeoutMs: 1000,
    idempotency: "IDEMPOTENT_WITH_KEY",
    networkRequired: false,
    filesystemBoundary: { mode: "NONE", allowedPaths: [] },
    approvalPolicyId: null,
    sourceImplementation: {
      module: "src/demo/screens/GitHubScreen.tsx",
      exportName: "GitHubScreen",
    },
  }),
  approvedTool({
    id: "tool.workflow.release-readiness",
    name: "Release-readiness transition",
    version: "1.0.0",
    description:
      "Requests or resumes a browser-local release-readiness transition after validator approval.",
    riskLevel: "HIGH",
    inputSchema: objectSchema(
      { issueKey: stringField, testedCommit: stringField, decision: { const: "release-ready" } },
      ["issueKey", "testedCommit", "decision"],
    ),
    outputSchema: objectSchema({ transitionRecorded: { type: "boolean" } }, ["transitionRecorded"]),
    sideEffects: ["Updates browser-local synthetic workflow state only after a bound approval."],
    requiredScopes: ["tool:invoke"],
    allowedStages: ["review"],
    timeoutMs: 1000,
    idempotency: "IDEMPOTENT_WITH_KEY",
    networkRequired: false,
    filesystemBoundary: { mode: "NONE", allowedPaths: [] },
    approvalPolicyId: "policy.release.validator-approval",
    sourceImplementation: {
      module: "src/demo/screens/GitHubScreen.tsx",
      exportName: "GitHubScreen",
    },
  }),
] satisfies readonly ToolDescriptorSource[];

const POLICY_PROVENANCE = {
  sourceCommit: SOURCE_COMMIT,
  independentlyAuthored: true,
  createdAt: "2026-07-17T12:00:00.000Z",
} as const;

function policy(
  source: Omit<ApprovalPolicySource, "kind" | "enabled" | "provenance">,
): ApprovalPolicySource {
  return {
    kind: "ApprovalPolicy",
    enabled: true,
    provenance: POLICY_PROVENANCE,
    ...source,
  };
}

export const approvalPolicySources = [
  policy({
    id: "policy.repository.read",
    name: "Repository reads",
    version: "1.0.0",
    description: "Allows bounded reads from synthetic issue and repository fixtures.",
    matcher: {
      toolIds: ["tool.issue.read", "tool.repository.search", "tool.repository.file.read"],
      riskLevels: ["READ_ONLY"],
    },
    mode: "ALLOW",
    requiredApproverScopes: [],
    requiredApproverPersonas: [],
    timeoutSeconds: 300,
    forbidSelfApproval: false,
    reasonRequired: false,
  }),
  policy({
    id: "policy.write.approved-targets",
    name: "Controlled writes inside approved targets",
    version: "1.0.0",
    description: "Requires a distinct code reviewer for a patch bounded by all write allow-lists.",
    matcher: {
      toolIds: ["tool.repository.patch.controlled"],
      stages: ["implement"],
      riskLevels: ["HIGH"],
      pathPatterns: ["src/**"],
      pathBoundary: "INSIDE_APPROVED_TARGETS",
    },
    mode: "REQUIRE_APPROVAL",
    requiredApproverScopes: ["diff:review"],
    requiredApproverPersonas: ["synthetic-code-reviewer"],
    timeoutSeconds: 1800,
    decisionCacheTtlSeconds: 300,
    forbidSelfApproval: true,
    reasonRequired: true,
  }),
  policy({
    id: "policy.write.outside-targets-deny",
    name: "Writes outside approved targets",
    version: "1.0.0",
    description:
      "Denies any controlled patch that escapes an agent, tool, or change-target boundary.",
    matcher: {
      toolIds: ["tool.repository.patch.controlled"],
      pathPatterns: ["**"],
      pathBoundary: "OUTSIDE_APPROVED_TARGETS",
    },
    mode: "DENY",
    requiredApproverScopes: [],
    requiredApproverPersonas: [],
    timeoutSeconds: 300,
    forbidSelfApproval: true,
    reasonRequired: true,
  }),
  policy({
    id: "policy.sandbox.network-deny",
    name: "Sandbox network access denied",
    version: "1.0.0",
    description: "Denies network-enabled sandbox requests in the functional local demonstration.",
    matcher: { toolIds: ["tool.sandbox.*"], networkAccess: true },
    mode: "DENY",
    requiredApproverScopes: [],
    requiredApproverPersonas: [],
    timeoutSeconds: 300,
    forbidSelfApproval: true,
    reasonRequired: true,
  }),
  policy({
    id: "policy.sandbox.validation-notify",
    name: "Fixed validation command",
    version: "1.0.0",
    description: "Allows the fixed local validation command and records a notification decision.",
    matcher: {
      toolIds: ["tool.sandbox.command"],
      stages: ["implement", "verify"],
      networkAccess: false,
    },
    mode: "NOTIFY",
    requiredApproverScopes: [],
    requiredApproverPersonas: [],
    timeoutSeconds: 600,
    forbidSelfApproval: false,
    reasonRequired: false,
  }),
  policy({
    id: "policy.evidence.finalized-deny",
    name: "Finalized evidence is immutable",
    version: "1.0.0",
    description: "Denies mutation after browser-local evidence is marked final.",
    matcher: { toolIds: ["tool.evidence.write"], evidenceFinalized: true },
    mode: "DENY",
    requiredApproverScopes: [],
    requiredApproverPersonas: [],
    timeoutSeconds: 300,
    forbidSelfApproval: true,
    reasonRequired: true,
  }),
  policy({
    id: "policy.evidence.write",
    name: "Mutable evidence write",
    version: "1.0.0",
    description: "Allows bounded synthetic evidence writes before finalization.",
    matcher: { toolIds: ["tool.evidence.write"], evidenceFinalized: false },
    mode: "ALLOW",
    requiredApproverScopes: [],
    requiredApproverPersonas: [],
    timeoutSeconds: 300,
    forbidSelfApproval: false,
    reasonRequired: false,
  }),
  policy({
    id: "policy.diff.human-review",
    name: "Human diff review",
    version: "1.0.0",
    description: "Allows an authorized reviewer to record inspection of a synthetic diff.",
    matcher: { toolIds: ["tool.repository.diff.inspect", "tool.workflow.diff-review"] },
    mode: "ALLOW",
    requiredApproverScopes: [],
    requiredApproverPersonas: [],
    timeoutSeconds: 300,
    forbidSelfApproval: false,
    reasonRequired: false,
  }),
  policy({
    id: "policy.release.validator-approval",
    name: "Release readiness requires validation approval",
    version: "1.0.0",
    description: "Requires a distinct validator persona before a release-readiness transition.",
    matcher: { toolIds: ["tool.workflow.release-readiness"], stages: ["review"] },
    mode: "REQUIRE_APPROVAL",
    requiredApproverScopes: ["validation:approve"],
    requiredApproverPersonas: ["synthetic-validator"],
    timeoutSeconds: 3600,
    decisionCacheTtlSeconds: 600,
    forbidSelfApproval: true,
    reasonRequired: true,
  }),
] satisfies readonly ApprovalPolicySource[];

export const modelPolicySources = [
  {
    kind: "ModelPolicy",
    id: "model.policy.delivery-balanced",
    name: "Delivery balanced",
    version: "2.0.0",
    description:
      "Provider-neutral offline policy for deterministic delivery-stage fixtures; no provider is contacted.",
    status: "APPROVED",
    providerCategory: "LOCAL_DETERMINISTIC",
    preferredModelId: "offline/delivery-balanced",
    allowedProviderIds: ["offline-mock"],
    allowedModelIds: ["offline/delivery-balanced", "offline/delivery-low"],
    fallbackOrder: ["offline/delivery-low"],
    reasoningProfile: "BALANCED",
    temperature: null,
    maximumInputTokens: 8000,
    maximumOutputTokens: 4000,
    maximumCostUsd: 0,
    maximumLatencyMs: 1000,
    allowedStages: ["intake", "spec", "plan", "targets", "implement", "verify", "review"],
    allowedTasks: ["ARTIFACT_DRAFT", "CODE_CHANGE", "INDEPENDENT_REVIEW"],
    independentReview: { required: false, modelId: null },
    executionMode: "OFFLINE_ONLY",
    sourceCommit: SOURCE_COMMIT,
    createdAt: CREATED_AT,
    updatedAt: "2026-07-17T21:00:00.000Z",
    approval: APPROVAL,
  },
  {
    kind: "ModelPolicy",
    id: "model.policy.local-gateway-opt-in",
    name: "Local gateway opt-in",
    version: "1.0.0",
    description:
      "Explicit developer-only policy for scoped routing through the local OpenAI-compatible gateway.",
    status: "APPROVED",
    providerCategory: "OPENAI_COMPATIBLE_LOCAL_GATEWAY",
    preferredModelId: "delivery-primary",
    allowedProviderIds: ["configured-local-gateway"],
    allowedModelIds: ["delivery-primary", "delivery-fallback", "delivery-review"],
    fallbackOrder: ["delivery-fallback"],
    reasoningProfile: "BALANCED",
    temperature: 0,
    maximumInputTokens: 2048,
    maximumOutputTokens: 512,
    maximumCostUsd: 0.05,
    maximumLatencyMs: 30000,
    allowedStages: ["implement", "verify", "review"],
    allowedTasks: ["CODE_CHANGE", "INDEPENDENT_REVIEW"],
    independentReview: { required: false, modelId: "delivery-review" },
    executionMode: "EXPLICIT_LOCAL_PROFILE",
    sourceCommit: SOURCE_COMMIT,
    createdAt: "2026-07-17T21:00:00.000Z",
    updatedAt: "2026-07-17T21:00:00.000Z",
    approval: APPROVAL,
  },
  {
    kind: "ModelPolicy",
    id: "model.policy.experimental-draft",
    name: "Experimental draft",
    version: "0.1.0",
    description: "Non-executable lifecycle fixture used to demonstrate fail-closed selection.",
    status: "DRAFT",
    providerCategory: "PROVIDER_NEUTRAL_SIMULATED",
    preferredModelId: "unselected-experimental-alias",
    allowedProviderIds: ["unconfigured-experimental-provider"],
    allowedModelIds: ["unselected-experimental-alias"],
    fallbackOrder: [],
    reasoningProfile: "HIGH",
    temperature: 0.2,
    maximumInputTokens: 12000,
    maximumOutputTokens: 4000,
    maximumCostUsd: 0.5,
    maximumLatencyMs: 60000,
    allowedStages: ["implement"],
    allowedTasks: ["CODE_CHANGE"],
    independentReview: { required: false, modelId: null },
    executionMode: "OFFLINE_ONLY",
    sourceCommit: SOURCE_COMMIT,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
  },
] satisfies readonly ModelPolicySource[];

export const memoryPolicySources = [
  {
    kind: "MemoryPolicy",
    id: "memory.policy.issue-bounded",
    name: "Issue-bounded context",
    version: "2.0.0",
    description:
      "Allows only current synthetic issue, approved artifacts, and toy-repository records.",
    status: "APPROVED",
    allowedRecordTypes: [
      "ARCHITECTURE_DECISION",
      "ENGINEERING_CONVENTION",
      "DOMAIN_RULE",
      "ISSUE_EVIDENCE",
      "USER_PREFERENCE",
      "CUSTOM",
    ],
    allowedSourceTypes: [
      "REPOSITORY",
      "ISSUE_FIXTURE",
      "DOCUMENTATION",
      "EVIDENCE",
      "USER_CONFIGURATION",
    ],
    allowedSensitivities: ["PUBLIC", "SYNTHETIC"],
    freshness: { maximumAgeSeconds: 604800, staleBehavior: "EXCLUDE" },
    maximumContextBytes: 1600,
    maximumEstimatedTokens: 400,
    priorRunEpisodicMemoryPermitted: false,
    retrievalMode: "DETERMINISTIC_RULES",
    selectionRuleVersion: "deterministic-context-v1",
    sourceCommit: CONTEXT_SOURCE_COMMIT,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    approval: APPROVAL,
  },
  {
    kind: "MemoryPolicy",
    id: "memory.policy.review-bounded",
    name: "Review evidence only",
    version: "2.0.0",
    description:
      "Limits review context to the tested diff, acceptance evidence, and approved artifacts.",
    status: "APPROVED",
    allowedRecordTypes: ["ARCHITECTURE_DECISION", "DOMAIN_RULE", "ISSUE_EVIDENCE", "CUSTOM"],
    allowedSourceTypes: ["REPOSITORY", "ISSUE_FIXTURE", "DOCUMENTATION", "EVIDENCE"],
    allowedSensitivities: ["PUBLIC", "SYNTHETIC"],
    freshness: { maximumAgeSeconds: 604800, staleBehavior: "EXCLUDE" },
    maximumContextBytes: 1400,
    maximumEstimatedTokens: 350,
    priorRunEpisodicMemoryPermitted: false,
    retrievalMode: "DETERMINISTIC_RULES",
    selectionRuleVersion: "deterministic-context-v1",
    sourceCommit: CONTEXT_SOURCE_COMMIT,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    approval: APPROVAL,
  },
  {
    kind: "MemoryPolicy",
    id: "memory.policy.implementation-episodic",
    name: "Bounded implementation context with episodic repair",
    version: "1.0.0",
    description:
      "Uses deterministic issue/repository rules and permits reviewed prior failure/fix records only for implementation.",
    status: "APPROVED",
    allowedRecordTypes: [
      "ARCHITECTURE_DECISION",
      "ENGINEERING_CONVENTION",
      "DOMAIN_RULE",
      "ISSUE_EVIDENCE",
      "PRIOR_FAILURE",
      "PRIOR_FIX",
      "USER_PREFERENCE",
      "CUSTOM",
    ],
    allowedSourceTypes: [
      "REPOSITORY",
      "ISSUE_FIXTURE",
      "DOCUMENTATION",
      "EVIDENCE",
      "USER_CONFIGURATION",
      "PRIOR_RUN",
    ],
    allowedSensitivities: ["PUBLIC", "SYNTHETIC"],
    freshness: { maximumAgeSeconds: 604800, staleBehavior: "EXCLUDE" },
    maximumContextBytes: 1900,
    maximumEstimatedTokens: 475,
    priorRunEpisodicMemoryPermitted: true,
    retrievalMode: "DETERMINISTIC_RULES",
    selectionRuleVersion: "deterministic-context-v1",
    sourceCommit: CONTEXT_SOURCE_COMMIT,
    createdAt: CREATED_AT,
    updatedAt: "2026-07-17T18:00:00.000Z",
    approval: APPROVAL,
  },
] satisfies readonly MemoryPolicySource[];

const AGENT_DEFAULTS = {
  kind: "AgentCard",
  version: "1.0.0",
  owner: "Synthetic delivery controls group",
  status: "APPROVED",
  inputSchema: INPUT_SCHEMA_REF,
  outputSchema: OUTPUT_SCHEMA_REF,
  modelPolicyId: "model.policy.delivery-balanced",
  memoryPolicyId: "memory.policy.issue-bounded",
  approvalPolicyIds: ["policy.registry.separation-of-duties"],
  maxDurationMs: 120000,
  maxToolCalls: 12,
  maxRepairAttempts: 2,
  tokenBudget: { maxInputTokens: 9000, maxOutputTokens: 3000, basis: "ESTIMATED" },
  costBudget: { maxEstimatedUsd: 0.35, basis: "ESTIMATED" },
  sourceCommit: SOURCE_COMMIT,
  createdAt: CREATED_AT,
  updatedAt: CREATED_AT,
  approval: APPROVAL,
} as const;

export const agentCardSources = [
  {
    ...AGENT_DEFAULTS,
    id: "agent.intake",
    name: "Intake Agent",
    description: "Normalizes one synthetic issue into a bounded intake artifact.",
    stageId: "intake",
    capabilities: ["issue normalization", "scope extraction", "ambiguity flagging"],
    skills: ["structured intake", "risk cue extraction"],
    allowedToolIds: ["tool.issue.read"],
    allowedWritePaths: ["artifacts/intake.json"],
    maxToolCalls: 2,
  },
  {
    ...AGENT_DEFAULTS,
    id: "agent.specification",
    name: "Specification Agent",
    description: "Creates testable synthetic acceptance criteria from approved intake context.",
    stageId: "spec",
    capabilities: ["acceptance criteria", "scope boundaries", "assumption recording"],
    skills: ["specification writing", "repository context lookup"],
    allowedToolIds: ["tool.issue.read", "tool.repository.search", "tool.repository.file.read"],
    allowedWritePaths: ["artifacts/spec.md"],
  },
  {
    ...AGENT_DEFAULTS,
    id: "agent.planning",
    name: "Planning Agent",
    description: "Emits an ordered implementation plan with risks and verification steps.",
    stageId: "plan",
    capabilities: ["task decomposition", "risk analysis", "verification planning"],
    skills: ["change sequencing", "dependency inspection"],
    allowedToolIds: ["tool.issue.read", "tool.repository.search", "tool.repository.file.read"],
    allowedWritePaths: ["artifacts/plan.md"],
  },
  {
    ...AGENT_DEFAULTS,
    id: "agent.change-target",
    name: "Change-Target Agent",
    description: "Constrains implementation to an explicit, inspectable file allow-list.",
    stageId: "targets",
    capabilities: ["file classification", "write-boundary declaration", "change impact mapping"],
    skills: ["repository search", "diff boundary reasoning"],
    allowedToolIds: [
      "tool.repository.search",
      "tool.repository.file.read",
      "tool.repository.diff.inspect",
    ],
    allowedWritePaths: ["artifacts/change-targets.json"],
  },
  {
    ...AGENT_DEFAULTS,
    id: "agent.implementation",
    name: "Implementation Agent",
    description: "Applies a human-approved bounded patch only in the disposable toy repository.",
    stageId: "implement",
    capabilities: ["bounded patching", "local validation", "repair attempt accounting"],
    skills: ["source editing", "test-guided repair", "diff inspection"],
    allowedToolIds: [
      "tool.repository.search",
      "tool.repository.file.read",
      "tool.repository.patch.controlled",
      "tool.sandbox.command",
      "tool.repository.diff.inspect",
      "tool.evidence.write",
    ],
    allowedWritePaths: ["src/**", "browser-local://evidence/**"],
    approvalPolicyIds: [
      "policy.registry.separation-of-duties",
      "policy.write.approved-targets",
      "policy.sandbox.validation-notify",
    ],
    maxToolCalls: 18,
    maxRepairAttempts: 2,
    memoryPolicyId: "memory.policy.implementation-episodic",
    sourceCommit: CONTEXT_SOURCE_COMMIT,
    updatedAt: "2026-07-17T18:00:00.000Z",
  },
  {
    ...AGENT_DEFAULTS,
    id: "agent.verification",
    name: "Verification Agent",
    description: "Runs the fixed local validation command and records synthetic evidence.",
    stageId: "verify",
    capabilities: [
      "fixed-command validation",
      "diff-to-evidence linkage",
      "failure classification",
    ],
    skills: ["test interpretation", "evidence packaging"],
    allowedToolIds: [
      "tool.repository.file.read",
      "tool.sandbox.command",
      "tool.repository.diff.inspect",
      "tool.evidence.write",
    ],
    allowedWritePaths: ["browser-local://evidence/**"],
    approvalPolicyIds: ["policy.registry.separation-of-duties", "policy.sandbox.validation-notify"],
  },
  {
    ...AGENT_DEFAULTS,
    id: "agent.review-assistant",
    name: "Review Assistant",
    description:
      "Summarizes the tested diff and flags risk; it cannot grant, record, or substitute for human approval.",
    stageId: "review",
    capabilities: ["diff summary", "risk flagging", "evidence cross-check"],
    skills: ["review preparation", "acceptance evidence comparison"],
    allowedToolIds: [
      "tool.repository.diff.inspect",
      "tool.evidence.write",
      "tool.workflow.diff-review",
      "tool.workflow.release-readiness",
    ],
    allowedWritePaths: ["browser-local://evidence/review-summary.json"],
    memoryPolicyId: "memory.policy.review-bounded",
    maxToolCalls: 6,
    maxRepairAttempts: 0,
  },
] satisfies readonly AgentCardSource[];

export const registryGeneratedAt = "2026-07-16T20:00:00.000Z";
