import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

import { format, resolveConfig } from "prettier";

import type { ModelGatewayPublicStatus } from "../src/demo/model-gateway/status";
import {
  MODEL_GATEWAY_IMPLEMENTATION_LABEL,
  MODEL_GATEWAY_VALIDATED_LABEL,
} from "../tools/model-gateway/contracts";
import { latestValidatedGatewayEvidence } from "../tools/model-gateway/evidence";

const root = resolve(import.meta.dirname, "..");
const checkOnly = process.argv.includes("--check");
const prettierConfig = (await resolveConfig(resolve(root, "package.json"))) ?? {};
const evidence = await latestValidatedGatewayEvidence(root);

const status: ModelGatewayPublicStatus = {
  schemaVersion: 1,
  implementation: "LiteLLM",
  implementationVersion: "1.92.0",
  imageDigest: "sha256:64d3547e0b131bf4638342e52c12bc46d6f1d9b8498e4b731ff31be5ab316ea9",
  label: evidence ? MODEL_GATEWAY_VALIDATED_LABEL : MODEL_GATEWAY_IMPLEMENTATION_LABEL,
  liveValidated: evidence !== null,
  sourceCommit: evidence?.sourceCommit ?? null,
  catalog: evidence?.catalog ?? null,
  disclosure: evidence
    ? "Recorded sanitized metadata from a developer-invoked local gateway run; the public browser does not contact the gateway."
    : "The adapter, credential lifecycle, policy enforcement, and fake-gateway tests are implemented. No live provider credential or successful live run was available for this checked-in build.",
};

const outputs = new Map<string, string>();
outputs.set(
  "src/demo/model-gateway/generated.ts",
  await format(
    `/* Generated by npm run model-gateway:generate. Do not edit directly. */\nimport type { ModelGatewayPublicStatus } from "./status";\n\nexport const modelGatewayStatus = ${JSON.stringify(status, null, 2)} as const satisfies ModelGatewayPublicStatus;\n`,
    { ...prettierConfig, parser: "typescript" },
  ),
);
outputs.set(
  "public/capabilities/model-gateway/status.json",
  await format(JSON.stringify(status), { ...prettierConfig, parser: "json" }),
);

let different = false;
for (const [relativePath, contents] of outputs) {
  const path = resolve(root, relativePath);
  if (checkOnly) {
    const current = await readFile(path, "utf8").catch(() => "");
    if (current !== contents) {
      different = true;
      process.stderr.write(`Generated model-gateway status is stale: ${relativePath}\n`);
    }
  } else {
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, contents, "utf8");
  }
}

if (different) process.exitCode = 1;
