import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

import { format, resolveConfig } from "prettier";

import { canonicalJson, contentHashInput } from "../src/demo/control-plane/registry/canonical";
import type {
  RegistryResource,
  RegistryResourceSource,
  RegistrySnapshot,
} from "../src/demo/control-plane/registry/contracts";
import {
  agentCardSources,
  memoryPolicySources,
  modelPolicySources,
  registryGeneratedAt,
  toolDescriptorSources,
} from "../src/demo/control-plane/registry/fixtures";
import { assertValidRegistryResource } from "../src/demo/control-plane/registry/validation";

const root = resolve(import.meta.dirname, "..");
const checkOnly = process.argv.includes("--check");
const prettierConfig = (await resolveConfig(resolve(root, "package.json"))) ?? {};

async function formatFile(contents: string, parser: "json" | "typescript"): Promise<string> {
  return format(contents, { ...prettierConfig, parser });
}

async function jsonFile(value: unknown): Promise<string> {
  return formatFile(JSON.stringify(value), "json");
}

function withHash(source: RegistryResourceSource): RegistryResource {
  const contentHash = createHash("sha256")
    .update(canonicalJson(contentHashInput(source)))
    .digest("hex");
  return assertValidRegistryResource({ ...source, contentHash });
}

const snapshot: RegistrySnapshot = {
  schemaVersion: 1,
  generatedAt: registryGeneratedAt,
  classification: "SYNTHETIC_PUBLIC_PORTFOLIO_FIXTURE",
  agents: agentCardSources.map(withHash).filter((item) => item.kind === "AgentCard"),
  tools: toolDescriptorSources.map(withHash).filter((item) => item.kind === "ToolDescriptor"),
  modelPolicies: modelPolicySources.map(withHash).filter((item) => item.kind === "ModelPolicy"),
  memoryPolicies: memoryPolicySources.map(withHash).filter((item) => item.kind === "MemoryPolicy"),
};

const schemaNames = [
  "common.schema.json",
  "agent-card.schema.json",
  "tool-descriptor.schema.json",
  "model-policy.schema.json",
  "memory-policy.schema.json",
  "stage-input.schema.json",
  "stage-output.schema.json",
] as const;

const outputs = new Map<string, string>();
const generatedTypeScript = await formatFile(
  `/* Generated by npm run registry:generate. Do not edit directly. */\nimport type { RegistrySnapshot } from "./contracts";\n\nexport const registrySnapshot = ${JSON.stringify(snapshot, null, 2)} as const satisfies RegistrySnapshot;\n`,
  "typescript",
);
outputs.set("src/demo/control-plane/registry/generated.ts", generatedTypeScript);
outputs.set("public/capabilities/registry.json", await jsonFile(snapshot));
outputs.set(
  "public/capabilities/agents/index.json",
  await jsonFile({
    schemaVersion: 1,
    classification: snapshot.classification,
    cards: snapshot.agents.map((agent) => ({
      id: agent.id,
      version: agent.version,
      contentHash: agent.contentHash,
      href: `/capabilities/agents/${agent.id}.json`,
    })),
  }),
);
for (const agent of snapshot.agents) {
  outputs.set(`public/capabilities/agents/${agent.id}.json`, await jsonFile(agent));
}
for (const schemaName of schemaNames) {
  const schema = await readFile(
    resolve(root, "src/demo/control-plane/registry/schemas", schemaName),
    "utf8",
  );
  outputs.set(`public/capabilities/schemas/${schemaName}`, await formatFile(schema, "json"));
}

let different = false;
for (const [relativePath, contents] of outputs) {
  const path = resolve(root, relativePath);
  if (checkOnly) {
    const current = await readFile(path, "utf8").catch(() => "");
    if (current !== contents) {
      different = true;
      process.stderr.write(`Generated registry artifact is stale: ${relativePath}\n`);
    }
  } else {
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, contents, "utf8");
  }
}

if (different) process.exitCode = 1;
